#pragma once

enum class InputKey {
    Escape = 0x1B,
    LeftMouse = 0x1,
    RightMouse = 0x2,
    LeftArrow = 0x25,
    UpArrow = 0x26,
    RightArrow = 0x27,
    DownArrow = 0x28,
    A = 0x41,
    B = 0x42,
    C = 0x43,
    D = 0x44,
    E = 0x45,
    F = 0x46,
    G = 0x47,
    H = 0x48,
    I = 0x49,
    J = 0x4A,
    K = 0x4B,
    L = 0x4C,
    M = 0x4D,
    N = 0x4E,
    O = 0x4F,
    P = 0x50,
    Q = 0x51,
    R = 0x52,
    S = 0x53,
    T = 0x54,
    U = 0x55,
    V = 0x56,
    W = 0x57,
    X = 0x58,
    Y = 0x59,
    Z = 0x5A,
    F1 = 0x70,
    F2 = 0x71,
    F3 = 0x72,
    F4 = 0x73,
    F5 = 0x74,
    F6 = 0x75,
    F7 = 0x76,
    F8 = 0x77,
    F9 = 0x78,
    F10 = 0x79,
    F11 = 0x7A,
    F12 = 0x7B,
    MouseWheelUp = 0x97, // Windows unassigned
    MouseWheelDown = 0x98 // Windows unassigned
};

const InputKey InputKeyCodes[] = {
    InputKey::Escape,
    InputKey::LeftMouse,
    InputKey::RightMouse,
    InputKey::LeftArrow,
    InputKey::UpArrow,
    InputKey::RightArrow,
    InputKey::DownArrow,
    InputKey::A,
    InputKey::B,
    InputKey::C,
    InputKey::D,
    InputKey::E,
    InputKey::F,
    InputKey::G,
    InputKey::H,
    InputKey::I,
    InputKey::J,
    InputKey::K,
    InputKey::L,
    InputKey::M,
    InputKey::N,
    InputKey::O,
    InputKey::P,
    InputKey::Q,
    InputKey::R,
    InputKey::S,
    InputKey::T,
    InputKey::U,
    InputKey::V,
    InputKey::W,
    InputKey::X,
    InputKey::Y,
    InputKey::Z,
    InputKey::F1, 
    InputKey::F2, 
    InputKey::F3, 
    InputKey::F4, 
    InputKey::F5, 
    InputKey::F6, 
    InputKey::F7, 
    InputKey::F8, 
    InputKey::F9, 
    InputKey::F10,
    InputKey::F11,
    InputKey::F12
};